config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root to: "phones#index"

  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'

  resources :phones, only: %i(index) do
    get 'get_info', on: :collection
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_channel, only: :index

  def index
  end

  def get_info
    phones_resource = params[:phones_resource]
    keyword = params[:keyword]
    channel = params[:channel]

    GetPhonesInfoJob.perform_later phones_resource, keyword, channel

    publish channel
  end

  private

  def publish channel
    ActionCable.server.broadcast(
      'phones_data',
      channel: channel,
      message: ApplicationController.render(
        partial: 'phones/phone_data',
        locals: { message: 'Search...' }
      )
    )
  end

  def set_channel
    @channel = SecureRandom.hex(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    = link_to "Phones Scanner", root_path, id: "logo"

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title Phones Scanner
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = action_cable_meta_tag

  body
    = render 'layouts/header'
    div.container
      = bootstrap_flash
      = yield

app/views/phones/_phone_data.html.slim
.dimentions
  h3 Dimentions:
  h4 = message

app/views/phones/index.html.slim
= form_tag get_info_phones_path, method: :get, remote: true, class: 'form-inline form-wrapper' do
  = text_field_tag :keyword, '', class: 'form-control input-lg', placeholder: 'keywords', style: "width:250px"
  = select_tag :phones_resource, options_for_select(BaseParser::PHONE_SERVICES), class: 'form-control input-lg', style: "width:180px"
  = hidden_field_tag :channel, @channel
  = submit_tag 'Search', class: 'form-control input-lg', id: 'submit', style: "width:150px"
   
div.main-text id="phones-data-#{@channel}"